require("martin.plugins-setup")
require("martin.core.options")
require("martin.core.keymaps")
require("martin.core.colorscheme")
require("martin.plugins.comment")
require("martin.plugins.nvim-tree")
require("martin.plugins.lualine")
require("martin.plugins.telescope")
